version: "3.9"

services:
  pgdb:
    container_name: pgdb
    image: postgis/postgis:15-3.3-alpine
    volumes:
      - type: volume
        source: pgdb_data
        target: /var/lib/postgresql/data/
      - type: bind
        source: ./initdb.d
        target: /docker-entrypoint-initdb.d/
    env_file:
      - ./docker.env
    ports:
      - 5432:5432

  webapi:
    container_name: webapi
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./docker.env
    volumes:
      - type: bind
        source: ./app
        target: /app/app
    ports:
      - 5000:5000

volumes:
  pgdb_data: {}
