# syntax = docker/dockerfile:1.2
FROM ubuntu:20.04

WORKDIR /app

RUN apt update
RUN apt install -y python3-pip libx11-6 libgl1-mesa-dev libpq-dev
RUN python3 -m pip install -U pip setuptools
COPY ./requirements.txt /tmp/
RUN --mount=type=cache,target=/root/.cache/pip \
    python3 -m pip install -r /tmp/requirements.txt

COPY ./app /app/app
COPY WebAPI.md ./wsgi.py /app/

CMD ["gunicorn", "wsgi:app", "--bind=0.0.0.0:5000", "--workers=2", "--timeout=600"]
